notifications:
  email:
    - hi@chunlianglyu.com
    - hpl1989@gmail.com

language: node_js
node_js:
  - "0.11"

cache:
  directories:
    - node_modules

install:
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update --standalone

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Immune to logouts, but not VM deprovisions!
  #- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
  - ./node_modules/protractor/bin/webdriver-manager start &
  - sleep 3

script: 
  - ./node_modules/protractor/bin/protractor --capabilities.browserName firefox protractor.conf.js
